---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  sealed-secrets-web
  namespace: flux-system
spec:
  interval: 15s
  timeout: 1m0s
  url: https://charts.bakito.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-web
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15s
  targetNamespace: sealed-secrets-web
  releaseName: "sealed-secrets"
  chart:
    spec:
      chart: sealed-secrets-web
      version: "2.17.1"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-web
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/ports/0/nodePort
                value: 30080
            target:
              kind: Service
              name: .*
  values:
    service:
      port: 80
      type: NodePort