---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dependency-track
  namespace: "flux-system"
spec:
  interval: 24h0m0s
  url: https://dependencytrack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
  namespace: "flux-system"
spec:
  interval: 30s
  serviceAccountName: kustomize-controller
  releaseName: "dependency-track"
  targetNamespace: "dependency-track"
  storageNamespace: "dependency-track"
  chart:
    spec:
      chart: dependency-track
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: dependency-track
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    apiServer:
      service:
        type: NodePort
        nodePort: 30443
    frontend:
      service:
        nodePort: 30080



