---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: peak-scale
  namespace: flux-system
spec:
  type: "oci"
  interval: 24h0m0s
  url: oci://ghcr.io/peak-scale/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule-argo-addon
spec:
  interval: 30s
  releaseName: "capsule-argo-addon"
  targetNamespace: "capsule-argo-addon"
  chart:
    spec:
      chart: capsule-argo-addon
      version: "0.1.0-alpha.2"
      sourceRef:
        kind: HelmRepository
        name: peak-scale
      interval: 24h
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  dependsOn:
    - name: capsule
    - name: argocd
  driftDetection:
    mode: enabled
  values:
    proxy:
      enabled: true
      crds:
        install: true
