---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name:  projectcapsule
spec:
  interval: 5m0s
  url: https://projectcapsule.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capsule
spec:
  interval: 10m
  targetNamespace: capsule-system
  releaseName: "capsule"
  chart:
    spec:
      chart: capsule
      version: "0.7.0-rc.1"
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      interval: 24h
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/userGroups"]
      target:
        group: capsule.clastix.io
        kind: CapsuleConfiguration
        name: default
  values:
    crds:
      install: true
    certManager:
      generateCertificates: true
    tls:
      # -- Start the Capsule controller that injects the CA into mutating and validating webhooks, and CRD as well.
      enableController: false
      # -- When cert-manager is disabled, Capsule will generate the TLS certificate for webhook and CRDs conversion.
      create: false
    manager:
      options:
        # -- Boolean, enforces the Tenant owner, during Namespace creation, to name it using the selected Tenant name as prefix, separated by a dash
        forceTenantPrefix: false
        # -- Override the Capsule user groups
        capsuleUserGroups: ["administrator"]