---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cert-manager
  releaseName: "cert-manager"
  storageNamespace: "cert-manager"
  chart:
    spec:
      chart: cert-manager
      version: "1.13.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 24h
  install:
    createNamespace: false
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    crds:
      enabled: true