---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
  labels:
    app.kubernetes.io/type: prod
spec:
  namespaceOptions:
    quota: 2
  owners:
  - name: alice
    kind: User
  - name: solar-users
    kind: Group
  additionalRoleBindings:
  - clusterRoleName: tenant-viewer
    subjects:
    - kind: User
      name: bob