apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
secretGenerator:
- name: sealing-key
  files:
  - tls.crt
  - tls.key
  type: "kubernetes.io/tls"
  options:
    labels:
      sealedsecrets.bitnami.com/sealed-secrets-key: active
