---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-secrets
  namespace: eso-vault
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: dev-secrets
    kind: SecretStore
  target:
    name: dev-secrets
  data: 
  - secretKey: api-key
    remoteRef:
      key: "dev-secrets/data/creds"
      property: "api-key" 