apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo
spec:
  generators:
    - list:
        elements:
          - stage: prod
          - stage: dev
  template:
    metadata:
      name: "podinfo-{{.stage}}"
    spec:
      destination:
        namespace: "wind-podinfo-{{.stage}}"
        server: https://kubernetes.default.svc
      project: wind
      source:
        path: solutions/multi-tenant-argo/example/plain/frontend
        repoURL: https://github.com/peak-scale/killercoda.git
        targetRevision: dev
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
