apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../../common/repos/headlamp.yaml
  - headlamp.flux.yaml
  - ../../../../common/repos/capsule.yaml
  - capsule.flux.yaml