---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  serviceAccountName: kustomize-controller
  interval: 15s
  targetNamespace: keycloak-system
  releaseName: "keycloak"
  chartRef:
    kind: OCIRepository
    name: keycloak
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: "enabled"
  values:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    production: true
    # https://www.keycloak.org/server/reverseproxy
    proxy: "edge"
    auth:
      adminUser: "keycloak"
      adminPassword: "capsule"
    extraEnvVars:
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: "KC_LOG_LEVEL"
      value: "debug"
    #- name: "KC_DB_SCHEMA"
    #  value: "keycloak"
    podSecurityContext:
      fsGroup: 1001
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    pdb:
      create: false
      minAvailable: 1
    ingress:
      enabled: false
    metrics:
      enabled: true
    postgresql:
      enabled: true
    service:
      nodePorts:
        http:  30100
        https: 30143
    extraVolumes:
    - name: themes
      emptyDir: {}
    extraVolumeMounts:
    - name: themes
      mountPath: /opt/bitnami/keycloak/themes/
    initContainers:
    - name: keycloak-theme
      image: docker.io/oliverbaehler/dev:theme
      imagePullPolicy: Always
      command:
      - sh
      - -c
      - |
          cp -R /themes/keywind/theme/keywind/ /temp/keywind
          chown -R 1001:root /temp
          chmod +x /temp/*
      volumeMounts:
      - name: themes
        mountPath: /temp/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    semver: ">= 24.4.10"