---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  projectcapsule
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://projectcapsule.github.io/charts