---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: peak-scale
  namespace: flux-system
spec:
  type: "oci"
  interval: 1m0s
  timeout: 1m0s
  url: oci://ghcr.io/peak-scale/charts/