---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  sops-secrets-operator
  namespace: flux-system
spec:
  interval: 15s
  timeout: 1m0s
  url: https://charts.bakito.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  targetNamespace: sops
  releaseName: "sops-secrets-operator"
  chart:
    spec:
      chart: sops-secrets-operator
      version: "0.20.4"
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    service:
      port: 80
      type: NodePort
    deployment:
      env:
        sealedSecretsControllerName: sealed-secrets
        sealedSecretsControllerNamespace: sealed-secrets
