---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
  labels:
    app.kubernetes.io/type: dev
  annotations:
    argo.addons.projectcapsule.dev/decouple: "true"
spec:
  owners:
  - name: alice
    kind: User